services:
  mongo:
    image: mongo:6.0
    container_name: chess-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - chess-net
    restart: always

  backend:
    build: ./backend
    container_name: chess-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chess
    depends_on:
      - mongo
    networks:
      - chess-net
    volumes:
      - ./backend:/app
      - /app/node_modules # Evita conflito com m√≥dulos locais

  frontend:
    build: ./frontend
    container_name: chess-frontend
    ports:
      - "9000:9000"
    depends_on:
      - backend
    networks:
      - chess-net
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodata:

networks:
  chess-net:
    driver: bridge
