services:
  mongo:
    image: mongo:6.0
    container_name: chess-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - chess-net
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chess-backend
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - ./backend:/app
      - /app/node_modules # Garante que o node_modules do container não seja sobrescrito pelo local
    # --- A MÁGICA ACONTECE AQUI ---
    command: >
      sh -c "npm install &&
             npm run build &&
             npm run start:prod"
    depends_on:
      - mongo
    networks:
      - chess-net

  frontend:
    build: ./frontend
    container_name: chess-frontend
    ports:
      - "9000:9000"
    depends_on:
      - backend
    networks:
      - chess-net
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodata:

networks:
  chess-net:
    driver: bridge
